// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1, arg2) {
  return window['go']['backend']['App']['AddRecord'](arg1, arg2);
}

export function CreateDataset(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateDataset'](arg1, arg2, arg3, arg4);
}

export function DeleteDataset(arg1) {
  return window['go']['backend']['App']['DeleteDataset'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['backend']['App']['DeleteRecord'](arg1);
}

export function GetDataset(arg1) {
  return window['go']['backend']['App']['GetDataset'](arg1);
}

export function GetDatasets() {
  return window['go']['backend']['App']['GetDatasets']();
}

export function GetRecord(arg1) {
  return window['go']['backend']['App']['GetRecord'](arg1);
}

export function GetRecords(arg1) {
  return window['go']['backend']['App']['GetRecords'](arg1);
}

export function ImportRecords(arg1, arg2) {
  return window['go']['backend']['App']['ImportRecords'](arg1, arg2);
}

export function UpdateDataset(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateDataset'](arg1, arg2, arg3, arg4);
}

export function UpdateRecord(arg1, arg2) {
  return window['go']['backend']['App']['UpdateRecord'](arg1, arg2);
}
