// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddRecord(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateDataset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.Dataset>;

export function DeleteDataset(arg1:string):Promise<void>;

export function DeleteRecord(arg1:string):Promise<void>;

export function GetDataset(arg1:string):Promise<database.Dataset>;

export function GetDatasets():Promise<Array<database.Dataset>>;

export function GetRecord(arg1:string):Promise<Record<string, any>>;

export function GetRecords(arg1:string):Promise<Array<Record<string, any>>>;

export function ImportRecords(arg1:string,arg2:string):Promise<number>;

export function UpdateDataset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.Dataset>;

export function UpdateRecord(arg1:string,arg2:string):Promise<Record<string, any>>;
