// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddRecord'](arg1, arg2, arg3);
}

export function CreateDataset(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateDataset'](arg1, arg2, arg3, arg4);
}

export function DeleteDataset(arg1) {
  return window['go']['backend']['App']['DeleteDataset'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['backend']['App']['DeleteFile'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['backend']['App']['DeleteRecord'](arg1);
}

export function GetDataset(arg1) {
  return window['go']['backend']['App']['GetDataset'](arg1);
}

export function GetDatasets() {
  return window['go']['backend']['App']['GetDatasets']();
}

export function GetFileAsBase64(arg1) {
  return window['go']['backend']['App']['GetFileAsBase64'](arg1);
}

export function GetFilePath(arg1) {
  return window['go']['backend']['App']['GetFilePath'](arg1);
}

export function GetRecord(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetRecord'](arg1, arg2, arg3);
}

export function GetRecords(arg1, arg2) {
  return window['go']['backend']['App']['GetRecords'](arg1, arg2);
}

export function GetRecordsWithRelations(arg1, arg2) {
  return window['go']['backend']['App']['GetRecordsWithRelations'](arg1, arg2);
}

export function GetRelatedRecords(arg1, arg2) {
  return window['go']['backend']['App']['GetRelatedRecords'](arg1, arg2);
}

export function ImportRecords(arg1, arg2) {
  return window['go']['backend']['App']['ImportRecords'](arg1, arg2);
}

export function ProcessRecord(arg1, arg2) {
  return window['go']['backend']['App']['ProcessRecord'](arg1, arg2);
}

export function ProcessRecordWithFiles(arg1, arg2) {
  return window['go']['backend']['App']['ProcessRecordWithFiles'](arg1, arg2);
}

export function ResetAllData() {
  return window['go']['backend']['App']['ResetAllData']();
}

export function SaveFiles(arg1, arg2) {
  return window['go']['backend']['App']['SaveFiles'](arg1, arg2);
}

export function UpdateDataset(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateDataset'](arg1, arg2, arg3, arg4);
}

export function UpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateRecord'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileChunk(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UploadFileChunk'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFileWithName(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UploadFileWithName'](arg1, arg2, arg3);
}
