// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddRecord(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function CreateDataset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.Dataset>;

export function DeleteDataset(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteRecord(arg1:string):Promise<void>;

export function GetDataset(arg1:string):Promise<database.Dataset>;

export function GetDatasets():Promise<Array<database.Dataset>>;

export function GetFileAsBase64(arg1:string):Promise<string>;

export function GetFilePath(arg1:string):Promise<string>;

export function GetRecord(arg1:string,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function GetRecords(arg1:string,arg2:boolean):Promise<Array<Record<string, any>>>;

export function GetRecordsWithRelations(arg1:string,arg2:boolean):Promise<Array<Record<string, any>>>;

export function GetRelatedRecords(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ImportRecords(arg1:string,arg2:string):Promise<number>;

export function ProcessRecord(arg1:Record<string, any>,arg2:boolean):Promise<void>;

export function ProcessRecordWithFiles(arg1:Record<string, any>,arg2:boolean):Promise<void>;

export function ResetAllData():Promise<void>;

export function SaveFiles(arg1:any,arg2:string):Promise<any>;

export function UpdateDataset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.Dataset>;

export function UpdateRecord(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<Record<string, any>>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UploadFileChunk(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<string>;

export function UploadFileWithName(arg1:string,arg2:string,arg3:string):Promise<string>;
