package database

const (
	DatasetIDDEXA                = "dexa"
	DatasetIDBloodwork           = "bloodwork"
	DatasetIDBloodMarker         = "blood_markers"
	DatasetIDBloodResult         = "blood_results"
	DatasetIDExperiment          = "experiments"
	DatasetIDMetric              = "metrics"
	DatasetIDDailyLog            = "daily_logs"
	DatasetIDMetricCategory      = "metric_categories"
	DatasetIDExperimentMetric    = "experiment_metrics"
	DatasetIDGratitudeJournal    = "gratitude_journal"
	DatasetIDAffirmation         = "affirmation"
	DatasetIDCreativityJournal   = "creativity_journal"
	DatasetIDQuestionJournal     = "question_journal"
	DatasetIDTimeEntries         = "time_entries"
	DatasetIDTimeCategories      = "time_categories"
	DatasetIDTimePlannerConfig   = "time_planner_configs"
	DatasetIDTodos               = "todos"
	DatasetIDPeople              = "people"
	DatasetIDMeetings            = "meetings"
	DatasetIDPersonAttributes    = "person_attributes"
	DatasetIDPersonNotes         = "person_notes"
	DatasetIDBirthdayReminders   = "birthday_reminders"
	DatasetIDPersonRelationships = "person_relationships"
)
