package database

func GetDEXAFields() []FieldDefinition {
	return []FieldDefinition{
		{
			Key:          "date",
			Type:         FieldTypeDate,
			DisplayName:  "Date",
			Description:  "Date when the DEXA scan was performed",
			IsSearchable: true,
		},
		{
			Key:         "fasted",
			Type:        FieldTypeBoolean,
			DisplayName: "Fasted",
			Description: "Whether the scan was performed while fasting",
		},
		{
			Key:         "total_body_fat_percentage",
			Type:        FieldTypePercentage,
			DisplayName: "Total Fat %",
			Description: "Total body fat percentage",
			IsOptional:  true,
		},
		{
			Key:          "fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Fat Tissue",
			Description:  "Total fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Lean Tissue",
			Description:  "Total lean tissue mass",
			Unit:         "lbs",
			IsSearchable: true,
		},
		{
			Key:         "total_mass_lbs",
			Type:        FieldTypeNumber,
			DisplayName: "Total Mass",
			Description: "Total body mass in pounds",
			Unit:        "lbs",
			IsOptional:  true,
		},
		{
			Key:          "bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "BMC",
			Description:  "Bone Mineral Content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "arms_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Arms Fat %",
			Description:  "Arms region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "arms_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Arms Mass",
			Description:  "Total arms mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "arms_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Arms Fat",
			Description:  "Arms fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "arms_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Arms Lean",
			Description:  "Arms lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "arms_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Arms BMC",
			Description:  "Arms bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "legs_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Legs Fat %",
			Description:  "Legs region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "legs_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Legs Mass",
			Description:  "Total legs mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "legs_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Legs Fat",
			Description:  "Legs fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "legs_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Legs Lean",
			Description:  "Legs lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "legs_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Legs BMC",
			Description:  "Legs bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "trunk_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Trunk Fat %",
			Description:  "Trunk region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "trunk_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Trunk Mass",
			Description:  "Total trunk mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "trunk_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Trunk Fat",
			Description:  "Trunk fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "trunk_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Trunk Lean",
			Description:  "Trunk lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "trunk_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Trunk BMC",
			Description:  "Trunk bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "android_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Android Fat %",
			Description:  "Android region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "android_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Android Mass",
			Description:  "Total android region mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "android_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Android Fat",
			Description:  "Android region fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "android_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Android Lean",
			Description:  "Android region lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "android_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Android BMC",
			Description:  "Android region bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "gynoid_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Gynoid Fat %",
			Description:  "Gynoid region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "gynoid_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Gynoid Mass",
			Description:  "Total gynoid region mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "gynoid_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Gynoid Fat",
			Description:  "Gynoid region fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "gynoid_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Gynoid Lean",
			Description:  "Gynoid region lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "gynoid_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Gynoid BMC",
			Description:  "Gynoid region bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "resting_metabolic_rate",
			Type:         FieldTypeNumber,
			DisplayName:  "RMR",
			Description:  "Resting metabolic rate",
			Unit:         "calories",
			IsSearchable: true,
		},
		{
			Key:          "android",
			Type:         FieldTypePercentage,
			DisplayName:  "Android %",
			Description:  "Android percentage",
			IsSearchable: false,
		},
		{
			Key:          "gynoid",
			Type:         FieldTypePercentage,
			DisplayName:  "Gynoid %",
			Description:  "Gynoid percentage",
			IsSearchable: false,
		},
		{
			Key:          "a_g_ratio",
			Type:         FieldTypeNumber,
			DisplayName:  "A/G Ratio",
			Description:  "Android to gynoid ratio",
			IsSearchable: false,
		},
		{
			Key:          "vat_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "VAT Mass",
			Description:  "Visceral adipose tissue mass",
			Unit:         "lbs",
			IsSearchable: true,
		},
		{
			Key:          "vat_volume_in3",
			Type:         FieldTypeNumber,
			DisplayName:  "VAT Volume",
			Description:  "Visceral adipose tissue volume",
			Unit:         "in³",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_head",
			Type:         FieldTypeNumber,
			DisplayName:  "Head BMD",
			Description:  "Bone mineral density of the head",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_arms",
			Type:         FieldTypeNumber,
			DisplayName:  "Arms BMD",
			Description:  "Bone mineral density of the arms",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_legs",
			Type:         FieldTypeNumber,
			DisplayName:  "Legs BMD",
			Description:  "Bone mineral density of the legs",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_trunk",
			Type:         FieldTypeNumber,
			DisplayName:  "Trunk BMD",
			Description:  "Bone mineral density of the trunk",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_ribs",
			Type:         FieldTypeNumber,
			DisplayName:  "Ribs BMD",
			Description:  "Bone mineral density of the ribs",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_spine",
			Type:         FieldTypeNumber,
			DisplayName:  "Spine BMD",
			Description:  "Bone mineral density of the spine",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_pelvis",
			Type:         FieldTypeNumber,
			DisplayName:  "Pelvis BMD",
			Description:  "Bone mineral density of the pelvis",
			Unit:         "g/cm²",
			IsSearchable: false,
		},
		{
			Key:          "bone_density_g_cm2_total",
			Type:         FieldTypeNumber,
			DisplayName:  "Total BMD",
			Description:  "Total bone mineral density",
			Unit:         "g/cm²",
			IsSearchable: true,
		},
		{
			Key:          "right_arm_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Right Arm Fat %",
			Description:  "Right arm region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "right_arm_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Arm Mass",
			Description:  "Total right arm mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_arm_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Arm Fat",
			Description:  "Right arm fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_arm_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Arm Lean",
			Description:  "Right arm lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_arm_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Arm BMC",
			Description:  "Right arm bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "left_arm_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Left Arm Fat %",
			Description:  "Left arm region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "left_arm_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Arm Mass",
			Description:  "Total left arm mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_arm_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Arm Fat",
			Description:  "Left arm fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_arm_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Arm Lean",
			Description:  "Left arm lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_arm_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Arm BMC",
			Description:  "Left arm bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "right_leg_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Right Leg Fat %",
			Description:  "Right leg region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "right_leg_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Leg Mass",
			Description:  "Total right leg mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_leg_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Leg Fat",
			Description:  "Right leg fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_leg_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Leg Lean",
			Description:  "Right leg lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "right_leg_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Right Leg BMC",
			Description:  "Right leg bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
		{
			Key:          "left_leg_total_region_fat_percentage",
			Type:         FieldTypePercentage,
			DisplayName:  "Left Leg Fat %",
			Description:  "Left leg region fat percentage",
			IsSearchable: false,
		},
		{
			Key:          "left_leg_total_mass_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Leg Mass",
			Description:  "Total left leg mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_leg_fat_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Leg Fat",
			Description:  "Left leg fat tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_leg_lean_tissue_lbs",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Leg Lean",
			Description:  "Left leg lean tissue mass",
			Unit:         "lbs",
			IsSearchable: false,
		},
		{
			Key:          "left_leg_bone_mineral_content",
			Type:         FieldTypeNumber,
			DisplayName:  "Left Leg BMC",
			Description:  "Left leg bone mineral content",
			Unit:         "g",
			IsSearchable: false,
		},
	}
}
