/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PaychecksImport } from './routes/paychecks'
import { Route as HabitsImport } from './routes/habits'
import { Route as DexaImport } from './routes/dexa'
import { Route as BloodworkImport } from './routes/bloodwork'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PaychecksRoute = PaychecksImport.update({
  id: '/paychecks',
  path: '/paychecks',
  getParentRoute: () => rootRoute,
} as any)

const HabitsRoute = HabitsImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRoute,
} as any)

const DexaRoute = DexaImport.update({
  id: '/dexa',
  path: '/dexa',
  getParentRoute: () => rootRoute,
} as any)

const BloodworkRoute = BloodworkImport.update({
  id: '/bloodwork',
  path: '/bloodwork',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bloodwork': {
      id: '/bloodwork'
      path: '/bloodwork'
      fullPath: '/bloodwork'
      preLoaderRoute: typeof BloodworkImport
      parentRoute: typeof rootRoute
    }
    '/dexa': {
      id: '/dexa'
      path: '/dexa'
      fullPath: '/dexa'
      preLoaderRoute: typeof DexaImport
      parentRoute: typeof rootRoute
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsImport
      parentRoute: typeof rootRoute
    }
    '/paychecks': {
      id: '/paychecks'
      path: '/paychecks'
      fullPath: '/paychecks'
      preLoaderRoute: typeof PaychecksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloodwork': typeof BloodworkRoute
  '/dexa': typeof DexaRoute
  '/habits': typeof HabitsRoute
  '/paychecks': typeof PaychecksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloodwork': typeof BloodworkRoute
  '/dexa': typeof DexaRoute
  '/habits': typeof HabitsRoute
  '/paychecks': typeof PaychecksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bloodwork': typeof BloodworkRoute
  '/dexa': typeof DexaRoute
  '/habits': typeof HabitsRoute
  '/paychecks': typeof PaychecksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bloodwork' | '/dexa' | '/habits' | '/paychecks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bloodwork' | '/dexa' | '/habits' | '/paychecks'
  id: '__root__' | '/' | '/bloodwork' | '/dexa' | '/habits' | '/paychecks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloodworkRoute: typeof BloodworkRoute
  DexaRoute: typeof DexaRoute
  HabitsRoute: typeof HabitsRoute
  PaychecksRoute: typeof PaychecksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloodworkRoute: BloodworkRoute,
  DexaRoute: DexaRoute,
  HabitsRoute: HabitsRoute,
  PaychecksRoute: PaychecksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bloodwork",
        "/dexa",
        "/habits",
        "/paychecks"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bloodwork": {
      "filePath": "bloodwork.tsx"
    },
    "/dexa": {
      "filePath": "dexa.tsx"
    },
    "/habits": {
      "filePath": "habits.tsx"
    },
    "/paychecks": {
      "filePath": "paychecks.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
