import {
  Home,
  Clock,
  CalendarDays,
  CheckCircle,
  Zap,
  Calendar,
  FlaskConical,
  BookOpen,
  Timer,
  PieChart,
  Activity,
  Database,
  Settings,
  Heart,
  CircleDot,
  Users,
  MessageCircle,
  NotebookPen,
  Gift,
  Network,
  UserRound,
  Ruler,
  Wallet,
  // Additional icons for route components
  Banknote,
  Receipt,
  Scale,
  FileText,
  Plus,
  HeartPulse,
  BarChart,
  RefreshCcw,
  Power,
  ChevronUp,
  ChevronDown,
  LayoutDashboard,
  TrendingUp,
  BarChart3,
  User,
  AlertTriangle,
  BookHeart,
  Lightbulb,
  HandHeart,
  Presentation,
  Tag,
  PlusSquare,
  List,
  Grid,
  ChevronLeft,
  ChevronRight,
  MenuIcon,
  DollarSign,
} from "lucide-react";

export const FEATURE_ICONS = {
  HOME: Home,
  TIME_TRACKER: Clock,
  DAILY_TRACKER: CalendarDays,
  TODOS: CheckCircle,
  METRIC_LOGGER: Zap,
  METRIC_CALENDAR: Calendar,
  EXPERIMENTS: FlaskConical,
  JOURNALING: BookOpen,
  TIME_PLANNER: Timer,
  DEXA_SCAN: PieChart,
  BLOODWORK: Activity,
  DATASETS: Database,
  SETTINGS: Settings,
  DEBUGGER: CircleDot,
  PEOPLE_CRM: Users,
  PEOPLE: UserRound,
  MEETINGS: MessageCircle,
  PERSON_NOTES: NotebookPen,
  BIRTHDAY_REMINDERS: Gift,
  RELATIONSHIPS: Network,
  CHATS: MessageCircle,
  ATTRIBUTES: Heart,
  BODY_MEASUREMENTS: Ruler,
  WEALTH: Wallet,
  // Additional utility icons
  BANKNOTE: Banknote,
  RECEIPT: Receipt,
  SCALE: Scale,
  FILE_TEXT: FileText,
  PLUS: Plus,
  HEART_PULSE: HeartPulse,
  BAR_CHART: BarChart,
  REFRESH: RefreshCcw,
  POWER: Power,
  CHEVRON_UP: ChevronUp,
  CHEVRON_DOWN: ChevronDown,
  LAYOUT_DASHBOARD: LayoutDashboard,
  TRENDING_UP: TrendingUp,
  BAR_CHART_3: BarChart3,
  USER: User,
  ALERT_TRIANGLE: AlertTriangle,
  BOOK_HEART: BookHeart,
  LIGHTBULB: Lightbulb,
  HAND_HEART: HandHeart,
  PRESENTATION: Presentation,
  TAG: Tag,
  PLUS_SQUARE: PlusSquare,
  LIST: List,
  GRID: Grid,
  CHEVRON_LEFT: ChevronLeft,
  CHEVRON_RIGHT: ChevronRight,
  MENU: MenuIcon,
  DOLLAR_SIGN: DollarSign,
};

export const getFeatureIcon = (iconName: string) => {
  return FEATURE_ICONS[iconName as keyof typeof FEATURE_ICONS] || Home;
};
